apiVersion: v1
kind: Service
metadata:
  name: tomcat-hello-world-workflow
  namespace: default
  labels:
    app.kubernetes.io/name: tomcat-hello-world-workflow
    kubernetes.azure.com/generator: draft
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: tomcat-hello-world-workflow
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80