name: Azure OpenAI Test

on: [workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest
    environment: testing
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
            
      - name: Run Azure OpenAI script
        run: |
          cd ./.github/workflows/scripts
          go run azure_openai_hello.go iterate-dockerfile-build
        env:
          AZURE_OPENAI_KEY: ${{ secrets.AZURE_OPENAI_KEY }}
          AZURE_OPENAI_ENDPOINT: ${{ secrets.AZURE_OPENAI_ENDPOINT }}
