name: Azure OpenAI Test

on: [workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Checkout Draft
        uses: actions/checkout@v3
        with:
          repository: davidgamero/draft
          branch: davidgamero/interactive-flag 
      - name: Build Draft
        run: |
          cd draft
          go build -o draft
          chmod +x draft
      - name: Generate with Draft
        run: |
          draft/draft create -vv --interactive=false --skip-file-detection
      
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
            
      - name: Run Azure OpenAI script
        run: |
          cd ./.github/workflows/scripts
          go run azure_openai_hello.go iterate-dockerfile-build
        env:
          AZURE_OPENAI_KEY: ${{ secrets.AZURE_OPENAI_KEY }}
          AZURE_OPENAI_ENDPOINT: ${{ secrets.AZURE_OPENAI_ENDPOINT }}
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7 #you must explicitly allow GitHub Actions to create pull requests under repository settings Actions > General > Workflow permissions.
        with: 
          branch: container-copilot/update
          delete-branch: true

